# -*- coding: utf-8 -*-
"""Regenerate notes/codebase_map.txt -- the browsable view of the map.

This used to be a hand-run one-off and went stale within a day, reporting
counts from before the tail-call and SDK-denominator fixes. It is generated by
rebuild.sh now so it cannot drift from symbols.json.

Two sections: subsystems by name prefix, then every translation unit with its
recovered names, which is what you actually read before opening Ghidra.
"""
import json, os, re, collections, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
try:
    from imstrlist import lookup as _im_lookup
    IMSTR = _im_lookup()
except Exception:
    IMSTR = {}
# units named after an IM id -- the game's own table says what each one is
IMNUM = re.compile(r'(?:^|/|bt)im(\d{3,4})\.c$')
SUB = [
    ('bt', 'battle system'), ('fv', 'free-roam view: 3D characters, motion'),
    ('fm', 'free-roam map: characters, movement, gimmicks'),
    ('fc', 'free-roam AI: NPC state, desires, schedules'),
    ('im', 'interaction memories -- the AI event scripts'),
    ('hh', 'hahig engine (Alfa System): objects, draw, tasks, memory'),
    ('gm', 'game shell: main loop, save, memory card'),
    ('ev', 'event sequencer and script data'),
    ('cp', 'character parameters: stats, items'),
    ('mem', 'memory card / search'), ('sound', 'audio'),
    ('gs', 'graphics primitives / GS packets'), ('cd', 'disc IO'),
]


def sub_of(unit):
    b = os.path.basename(unit)
    for p, _ in SUB:
        if b.startswith(p):
            return p
    return '(other)'


def main():
    syms = json.load(open(os.path.join(ROOT, 'symbols', 'symbols.json')))
    rows = collections.defaultdict(lambda: [0, 0])
    units = collections.defaultdict(lambda: [0, []])
    sdk = unattr = unattr_named = 0
    for rel, info in syms.items():
        for f in info['functions']:
            u = f.get('unit')
            nm = f.get('name') if f.get('name_source') else None
            if f.get('library'):
                sdk += 1
                continue
            if not u:
                unattr += 1
                unattr_named += bool(nm)
                continue
            s = sub_of(u)
            rows[s][0] += 1
            rows[s][1] += bool(nm)
            key = (rel, u)
            units[key][0] += 1
            if nm:
                units[key][1].append((f['addr'], nm))

    out = ['NGE2 codebase map', '=================', '',
           'Generated by tools/codebase_map.py -- do not edit by hand.', '',
           f'{"subsystem":52} {"funcs":>6} {"named":>6}', '']
    for p, desc in SUB:
        if p in rows:
            n, k = rows[p]
            out.append(f'{p+"  "+desc:52.52} {n:6} {k:6}')
    for k in sorted(rows):
        if k not in dict(SUB):
            n, m = rows[k]
            out.append(f'{k:52.52} {n:6} {m:6}')
    out += [f'{"(Sony SDK / libc)":52} {sdk:6} {0:6}',
            f'{"(unattributed)":52} {unattr:6} {unattr_named:6}', '',
            '', 'Translation units', '-----------------', '']
    for (rel, u), (n, names) in sorted(units.items(), key=lambda kv: (-kv[1][0], kv[0])):
        m = IMNUM.search(u)
        desc = ''
        if m:
            d = IMSTR.get(int(m.group(1)))
            if d and d != '(unused)':
                desc = f'   -- {d}'
        out.append(f'{u}  [{rel}]  {n} functions, {len(names)} named{desc}')
        for a, nm in sorted(names)[:40]:
            out.append(f'    {a:08X}  {nm}')
        if len(names) > 40:
            out.append(f'    ... and {len(names)-40} more')
        out.append('')
    p = os.path.join(ROOT, 'notes', 'codebase_map.txt')
    open(p, 'w').write('\n'.join(out) + '\n')
    print(f'   wrote {p}  ({len(units)} units)')


main()
